config/routes.rb
Rails.application.routes.draw do

  get 'landing/index'
  get 'games/index'
  get 'playoffs/index'
  get 'playoffs/new'
  get 'playoff/index'
  get 'playoff/new'
  root to: 'landing#index'
  resources :tournaments
  get '/tournaments', to: 'tournaments#index'
  get    '/tournaments/:id/add_team',    to: 'tournaments#add_team', as: :add_team
  post   '/tournaments/:id/add_team',    to: 'tournaments#add_to_tournament'
  delete '/tournaments/:id/delete_team', to: 'tournaments#delete_team', as: :delete_team

  get   '/tournaments/:id/poolplay',           to: 'poolplays#index', as: :poolplay
  get   '/tournaments/:id/poolplay/new',       to: 'poolplays#new',   as: :new_poolplay
  get   '/tournaments/:id/poolplay/temp_pool', to: 'poolplays#create_temporary_pool', as: :create_temp_pool
  post  '/tournaments/:id/poolplay',           to: 'poolplays#create'
  get   '/tournaments/:id/poolplay/edit',      to: 'poolplays#edit',  as: :results_poolplay
  patch '/tournaments/:id/poolplay',           to: 'poolplays#update'
  put   '/tournaments/:id/poolplay',           to: 'poolplays#update'
  post  '/tournaments/:id/poolplay_finished',  to: 'poolplays#poolplay_finished', as: :poolplay_finished
  get   '/tournaments/:id/poolplay/leaderboard',   to: 'poolplays#leaderboard', as: :poolplay_leaderboard

  get   '/tournaments/:id/playoffs',             to: 'playoffs#index', as: :playoffs
  post  '/tournaments/:id/playoffs',             to: 'playoffs#create'
  get   '/tournaments/:id/playoffs/edit',        to: 'playoffs#edit',  as: :results_playoffs
  patch '/tournaments/:id/playoffs',             to: 'playoffs#update'
  put   '/tournaments/:id/playoffs',             to: 'playoffs#update'
  post  '/tournaments/:id/playoffs_finished',    to: 'playoffs#playoffs_finished', as: :playoffs_finished
  get   '/tournaments/:id/final_results',        to: 'playoffs#final_results', as: :final_results
  get   '/tournaments/:id/playoffs/leaderboard', to: 'playoffs#leaderboard', as: :playoffs_leaderboard


  # resources :users
  get '/players',          to: 'users#index'
  get '/signup',           to: 'users#new', as: :new_session
  post '/signup',          to: 'users#create'
  get '/players/:id',      to: 'users#show', as: :player
  get '/players/:id/edit', to: 'users#edit', as: :edit_player
  patch '/players/:id',    to: 'users#update'
  put '/players/:id',      to: 'users#update'

  get   '/players/:id/edit_password', to: 'users#edit_password', as: :edit_password
  patch '/players/:id/edit_password', to: 'users#update_password'
  put   '/players/:id/edit_password', to: 'users#update_password'




  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :teams
  has_many :tournaments, through: :teams

  has_secure_password

  validates :first_name, presence: true
  # validates :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, on: :create, length: {minimum: 6}

  def admin?
    self.admin
  end

  def self.available_users(tourn_id)
    teams_already_added = Tournament.find(tourn_id).teams.map { |team| team.user_id }
    User.where.not(id: teams_already_added)
  end

  #Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns random token for remember me cookie
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest,  nil)
  end

  # Returns true if the given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def tournaments_played
    # tournaments ids from past tournaments played in
    # team-playoffs ids from
    # just for kob tournaments now (lookup just user_id in Team)
    Team.where(user_id: self.id, playoffs: true).map do |team|
      tourn = Tournament.find_by_id(team.tournament_id)
      points = tourn.points_earned_kob
      place = team.place.to_i
      points_earned = points[place - 1]
      { tourn_name: tourn.name, tourn_id: tourn.id, tourn_date: tourn.date, place: place, points: points_earned }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user#, only: [:show, :edit, :index, :edit_password, :update_password]
  before_action :make_read_only, only: [:new]

  def index
    @users = User.all.sort_by {|player| player.points}.reverse
  end

  def new
    @new_user = User.new
  end

  def create
    @admin = nil
    if current_user && current_user.admin
      @admin = current_user
    end

    @new_user = User.new(user_params)
    if @new_user.save
      if @admin
        redirect_to players_path
      else
        log_in @new_user
        flash[:success] = "You have signed up successfully"
        redirect_to tournaments_path
      end
    else
      flash.now[:danger] = "You have not signed up successfully"
      render :new
    end
  end

  def show
    @player = User.find_by_id(params[:id])
    players = User.all.sort_by {|player| player.points}.reverse
    @ranking = players.index(@player) + 1
    @tournaments = @player.tournaments_played
  end

  def edit
    restrict_access(params[:id].to_i)
  end

  def update
    restrict_access(params[:id].to_i)
  end

  def edit_password
    restrict_access(params[:id].to_i)

    @user = current_user

  end

  def update_password
    @user = current_user

    @user.update(user_params)

    if @user.save
      flash[:success] = "You have changed your password"
      redirect_to player_path(@user)
    else
      flash.now[:danger] = "Password not changed"
      render 'edit_password'
    end
  end

  private

    def set_user
      @user = current_user
    end

    def restrict_access(profile_id)
      if @user.nil? || @user.id != profile_id
        flash[:danger] = "You do not have access to that page"
        redirect_to root_path
      end
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :points, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h2 class="text-center">Register</h2>
<div>

  <div class="form_container auth">
    <%= form_for(@new_user, url: signup_path, html: {method: 'post'}) do |f| %>
      <%= render 'shared/errors', object: @new_user %>

      <div class="form-group row">
        <%= f.label :first_name, value: "First name:", class: 'col-3 col-form-label'  %>
        <div class="col-9 d-flex flex-column">
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :last_name, value: "Last name:", class: 'col-3 col-form-label'  %>
        <div class="col-9">
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :email, value: "Email:", class: 'col-3 col-form-label'  %>
        <div class="col-9">
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :password, value: "Password:", class: 'col-3 col-form-label'  %>
        <div class="col-9">
          <%= f.text_field :password, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :password_confirmation, value: "Confirm Password:", class: 'col-3 col-form-label'  %>
        <div class="col-9">
          <%= f.text_field :password_confirmation, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="">
          <%= f.submit "Register", class: "btn btn-primary btn-block" %>
        </div>
        <div class="mt-2">
          <%= link_to "Cancel", root_path, class: "btn btn-danger btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_tournament.html.erb
<tr>
  <td class="tourn-field"><%= link_to tournament[:tourn_name], playoffs_path(tournament[:tourn_id])%></td>
  <td class="date"><%= normalize_date_table(tournament[:tourn_date]) %></td>
  <td class="place" ><%= tournament[:place].ordinalize %></td>
  <td class="points"><%= tournament[:points] %></td>
</tr>

app/views/users/_user.html.erb
<tr class="d-flex">
  <td class="col-6"><%= link_to "#{user.first_name.capitalize} #{user.last_name || ''}", player_path(user.id) %></td>
  <td class="col-3"><%= (user_counter + 1).ordinalize %></td>
  <td class="col-3"><%= user.points %></td>
</tr>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/edit_password.html.erb
<h2 class="text-center">Change Password</h2>
<div>
  <div class="form_container auth">
    <%= form_for(@user, url: edit_password_path(@user), html: {method: 'patch'}) do |f| %>
      <%= render 'shared/errors', object: @user %>

      <div class="form-group row">
        <%= f.label :password, value: "New Password:", class: 'col-3 col-form-label'  %>
        <div class="col-9">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :password_confirmation, value: "Confirm New Password:", class: 'col-3 col-form-label'  %>
        <div class="col-9">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="">
          <%= f.submit "Change Password", class: "btn btn-primary btn-block" %>
        </div>
        <div class="mt-2">
          <%= link_to "Cancel", player_path(@user), class: "btn btn-danger btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div>
  <div class="table-responsive ">
    <table class="table align-center" id="players-list-table">
      <thead>
        <tr class="d-flex">
          <th scope="col" class="col-6" >Player</th>
          <th scope="col" class="col-3">Ranking</th>
          <th scope="col" class="col-3">Points</th>
        </tr>
      </thead>
      <tbody>
        <% if @users.empty? %>
          <tr>
            <td colspan="4">No Players</td>
          </tr>
        <% else %>
          <%= render @users, cache: true %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<div class="col-md-4 mr-auto ml-auto">
  <div class="card card-body bg-info text-white mb-3">
    <div class="text-center">
      <h1 class="display-4 text-center"><%= @player.first_name %> <%= @player.last_name %></h1>
      <h5>Ranking: <%= @ranking.ordinalize %></h5>
      <div class="d-flex justify-content-around">
        <% if @user && (@user.id == @player.id) %>
          <span><%= link_to "Edit Profile", edit_player_path(@player), class: "text-dark" %></span>
          <span><%= link_to "Change password", edit_password_path(@player), class: "text-dark" %></span>
        <% end %>
      </div>
    </div>
  </div>
</div>
<h2>Past tournaments</h2>
<table class="table">
  <thead>
    <tr>
      <th class="tourn-field" scope="col">Tournament</th>
      <th class="date" scope="col">Date</th>
      <th class="place"scope="col">Place</th>
      <th class="points" scope="col">Points Earned</th>
    </tr>
  </thead>
  <tbody>
    <% if @tournaments.empty? %>
      <tr>
        <td colspan="4">N/A</td>
      </tr>
    <% else %>
      <% @tournaments.each do |tourn| %>
        <%= render 'tournament', tournament: tourn, cache: true %>
      <% end %>
    <% end %>
  </tbody>
</table>