config/routes.rb
Rails.application.routes.draw do

  get 'landing/index'
  get 'games/index'
  get 'playoffs/index'
  get 'playoffs/new'
  get 'playoff/index'
  get 'playoff/new'
  root to: 'landing#index'
  resources :tournaments
  get '/tournaments', to: 'tournaments#index'
  get    '/tournaments/:id/add_team',    to: 'tournaments#add_team', as: :add_team
  post   '/tournaments/:id/add_team',    to: 'tournaments#add_to_tournament'
  delete '/tournaments/:id/delete_team', to: 'tournaments#delete_team', as: :delete_team

  get   '/tournaments/:id/poolplay',           to: 'poolplays#index', as: :poolplay
  get   '/tournaments/:id/poolplay/new',       to: 'poolplays#new',   as: :new_poolplay
  get   '/tournaments/:id/poolplay/temp_pool', to: 'poolplays#create_temporary_pool', as: :create_temp_pool
  post  '/tournaments/:id/poolplay',           to: 'poolplays#create'
  get   '/tournaments/:id/poolplay/edit',      to: 'poolplays#edit',  as: :results_poolplay
  patch '/tournaments/:id/poolplay',           to: 'poolplays#update'
  put   '/tournaments/:id/poolplay',           to: 'poolplays#update'
  post  '/tournaments/:id/poolplay_finished',  to: 'poolplays#poolplay_finished', as: :poolplay_finished
  get   '/tournaments/:id/poolplay/leaderboard',   to: 'poolplays#leaderboard', as: :poolplay_leaderboard

  get   '/tournaments/:id/playoffs',             to: 'playoffs#index', as: :playoffs
  post  '/tournaments/:id/playoffs',             to: 'playoffs#create'
  get   '/tournaments/:id/playoffs/edit',        to: 'playoffs#edit',  as: :results_playoffs
  patch '/tournaments/:id/playoffs',             to: 'playoffs#update'
  put   '/tournaments/:id/playoffs',             to: 'playoffs#update'
  post  '/tournaments/:id/playoffs_finished',    to: 'playoffs#playoffs_finished', as: :playoffs_finished
  get   '/tournaments/:id/final_results',        to: 'playoffs#final_results', as: :final_results
  get   '/tournaments/:id/playoffs/leaderboard', to: 'playoffs#leaderboard', as: :playoffs_leaderboard


  # resources :users
  get '/players',          to: 'users#index'
  get '/signup',           to: 'users#new', as: :new_session
  post '/signup',          to: 'users#create'
  get '/players/:id',      to: 'users#show', as: :player
  get '/players/:id/edit', to: 'users#edit', as: :edit_player
  patch '/players/:id',    to: 'users#update'
  put '/players/:id',      to: 'users#update'

  get   '/players/:id/edit_password', to: 'users#edit_password', as: :edit_password
  patch '/players/:id/edit_password', to: 'users#update_password'
  put   '/players/:id/edit_password', to: 'users#update_password'




  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  include PoolplaysHelper
  has_many :teams, dependent: :destroy
  has_many :users, through: :teams
  has_many :games, dependent: :destroy

  validates :name, presence: true
  validates :date, presence: true
  validates :tournament_type, presence: true

  def sort_teams_by_points
    self.teams.sort {|a, b| b.total_points <=> a.total_points}
  end

  # get all poolplay Game objects
  def poolplay_games
    self.games.select { |game| game.version == 'poolplay'}
  end

  # get all playoff Game objects
  def playoff_games
    self.games.select { |game| game.version == 'playoff'}
  end

  # get all Team objects from poolplay
  def poolplay_team_objects
    self.teams.select { |team| !team.playoffs }
  end

  def poolplay_team_ids
    self.teams.select {|team| !team.playoffs }.map { |team| team.id }
  end

  # selects Team objects based on court id
  ## then sorts teams based on record then point differential
  def get_court_standings(court_id, playoff_bool)
    sort_group_of_teams(self.teams.select {|team| team.court_id == court_id && team.playoffs == playoff_bool })
  end

  # final results for kob tournament
  def final_results_list
    winners = sort_group_of_teams(self.teams.select { |team| team.playoffs && team.court_id == 100 })
    losers = sort_group_of_teams(self.teams.select { |team| team.playoffs && team.court_id != 100 })

    #only for kob, game play will not have a losers court
    ## winner of consolation court kob, become overall 4th place
    if (losers)
      third_place = losers.shift
      winners.insert(3, third_place).concat(losers)
    end
    winners
  end

  #######  CREATE AND SAVE DIFFERENT PLAY TYPES ###############

  # creates a hash for initial kob poolplay round
  # randomly assigns team_ids to courts, with 4 teams/players to a court
  def create_random_kob_poolplay
    if self.teams.length % 4 != 0
      return false
    end
    randomly_assign_kob_players_to_courts(self.poolplay_team_ids)
    ##{1: [3, 4, 8, 5], 2: [1, 2, 7, 6]}
  end

  # Creates team object for poolplay
  ##
  def create_team_poolplay
    pool = self.poolplay_teams # Team objects
    save_team_play_to_database(tournament_id, pool, "poolplay")
  end

  # creates playoffs games when tournament_type is set to kob
  ## takes in teams array already sorted by record and diff
  def create_kob_playoffs
    playoffs = {}
    court = 100
    sorted_users = self.final_poolplay_rankings # returns Team objects
    until sorted_users.empty?
      teams = sorted_users.shift(4).map do |team|
        save_kob_team_to_database(team.user_id, team.team_name, court, true)
      end
      playoffs[court] = teams
      court += 1
    end
    # playoffs => {100: [Teamobjects], 101: [Team_objects]}
    ## => transform into { 100: [team_ids...], 101: [team_ids]}
    ###
    playoffs.keys.each do |court|
      playoffs[court].map! {|team| team.id}
    end
    # create new Team objects for playoffs
    # creates a hash with court ids as keys and array of team ids as values
    # playoffs = hash of team ids separated by court number
    self.save_kob_games_to_database(playoffs, "playoff")
  end

  def final_poolplay_rankings
    sort_group_of_teams(self.poolplay_team_objects)
  end

  def final_poolplay_rankings_by_user_id
    final_poolplay_rankings.map {|team| team.user_id}
  end

  # creates playoffs games when tournament_type is set to kob/team
  ## takes in array of array of Team objects already sorted
  ### return an array of arrays of team ids sorted by record and diff
  def create_teams_from_kob_playoffs
    seeds = {}
    seed = 1
    sorted_teams = final_poolplay_rankings_by_user_id
    # creates an array of all teams in tournament sorted by record then points
    until sorted_teams.empty?
      ## remove first 2 teams
      ## create a new Team object with
      player1_id, player2_id = sorted_teams.shift(2)
      Team.create()
      seeds[seed] = sorted_teams.shift(2)
      seed += 1
    end
    seeds # hash seed num as keys and array of 2 team ids as value
    save_teams_playoffs_to_database(tournament.id, seeds, "playoffs")
  end

  # creates playoffs games when tournament_type is set to team
  def create_teams_from_teams_playoffs()
  end

  # used to save Game objects all tourn_types
  ## pool = {100 => ["3/4-1/2", "1/4-2/3", "2/4-1/3"], 101 => ...}
  ### version => poolplay or playoff
  def save_kob_games_to_database(pool, version)
    pool.keys.each do |group|
      #["3/4-1/2", "1/4-2/3", "2/4-1/3"]
      generate_kob_games(pool[group]).each do |game|
        if Game.create( tournament_id: self.id,
                        team_ids: game,
                        court_id: group,
                        version: version)
        else
          return false
        end
      end
    end
    true
  end

  # takes in hash of court_ids as keys and array of team_ids as properties
  ## updates Team court_id field
  ### used when creating random kob courts before starting poolplay
  def update_team_court_id(pool)
    pool.keys.each do |court_id|
      pool[court_id].each do |team_id|
        Team.find_by_id(team_id.to_i)
          .update(court_id: court_id)
      end
    end
  end

  def save_kob_team_to_database(player_id, team_name, court_id, version)
    Team.create(user_id: player_id, tournament_id: self.id,
                team_name: team_name, court_id: court_id, playoffs: version )
  end

  def points_earned_kob
    num_of_teams = self.teams.select { |team| team.playoffs }.length
    if num_of_teams == 4
      return [100, 50, 25, 20]
    else
      points = [100, 50, 25, 20, 20]
      until points.length == num_of_teams
        points << 10
      end
      return points
    end
  end

  def end
    self.update!(closed: true)
    teams = self.final_results_list
    points = self.points_earned_kob
    # private method
    update_users_points(teams, points)
  end

  private

  def sort_group_of_teams(teams)
    teams.sort_by  do |team|
      team_wins, team_losses = team.pool_record.split("-").map(&:to_i)
      [team_wins, team.pool_diff]
    end.reverse
  end
  #takes in Game object
  #returns an array of teams [1, 2, 4, 5]
  def get_team_ids(game)
    team_ids = game.team_ids # "1/2-4/5"
    team_ids.split("-").map do |team| #["1/2", "4/5"]
      team.split("/")
    end.flatten.map(&:to_i)
  end

  # takes all playoff game instances
  # [{id, tourn_id, round, team_ids, winner}, ...]
  def get_final_placings_team_play(playoff_games)
    all_seeds = playoff_games.select {|game| game.round == 1}.map do |game|
       game.team_ids.split(",")
    end.flatten

    results = []

    sorted_by_round = playoff_games.sort {|game1, game2| game2.round <=> game1.round}
    i = 0
    until sorted_by_round.empty?
      break if sorted_by_round[i].nil?
      seeds = sorted_by_round[i].team_ids.split(",") #in team play, team_ids will be seed #s
      next_in = seeds.select {|seed| !results.include?(seed)}

      if results.empty?
        winner = sorted_by_round[i].winner
        loser = seeds.select {|seed| seed != winner}.first
        results.push(winner, loser)
      elsif next_in
        results.push(next_in)
        results.flatten!
      end
      sorted_by_round.shift
      i += 1
    end
    results.flatten!
    all_seeds.each do |seed|
      results.push(seed) if !results.include?(seed)
    end
    results
  end

  def randomly_assign_kob_players_to_courts(teams)
    court = 1
    result = {court => []}
    until teams.empty?
      team = teams.slice!(rand(teams.length))
      if result[court].length == 4
        court += 1
        result[court] = [team]
      else
        result[court].push(team)
      end
    end
    result #{1: [3, 4, 8, 5], 2: [1, 2, 7, 6]}
  end

  def generate_kob_games(group)
    teams = group.permutation(2).to_a.map { |team| team.sort() }.uniq
    #teams = [[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]]
    games = []
    until teams.empty? do
      team1 = teams.slice!(rand(teams.length))
      team2 = nil
      while team2.nil? || team2.any? { |player| team1.include?(player) } do
        random_index = rand(teams.length)
        team2 = teams[random_index]
      end
      teams.slice!(random_index)
      game = "#{team1[0]}/#{team1[1]}-#{team2[0]}/#{team2[1]}"
      games.push(game)
    end
    games
  end

  def update_users_points(teams, points)
    teams.each_with_index do |team, i|
      user = team.user
      team.update!(place: i + 1)
      user.update!(points: user.points + points[i])
    end
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  include TournamentsHelper
  include PoolplaysHelper

  before_action :set_tournament, except: [:index, :new, :create]#only: [:show, :edit, :add_team, :add_to_tournament, :update, :pool_play, :destroy]
  before_action :set_user
  before_action :restrict_access, only: [:new, :create, :edit, :join, :destroy]
  # before_action :set_teams, only: [:show, :pool_play]

  def landing
    
  end
  def index
    # @tournaments = Tournament.all
    @tournaments_active = Tournament.where(closed: false)#.order("date DESC")
    @tournaments_closed = Tournament.where(closed: true)#.order("date DESC")
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)
    if @tournament.save
      flash[:success] = "Tournament has been created"
      redirect_to tournaments_path
    else
      flash.now[:danger] = "Tournament has not been created"
      render :new
    end
  end

  def show
    @date = Time.new(@tournament.date)
  end

  def edit
  end

  # shows add_team form for user or admin
  def add_team
    @players = User.available_users(@tournament.id)
    unless @tournament.registration_open
      flash[:danger] = "Registration is closed"
      redirect_to tournament_path(@tournament)
    end
  end


  def add_to_tournament
    if @tournament.tournament_type == 'kob' || @tournament.tournament_type == 'kob/team'
      if params[:players] # adding mulitple players (only admin)
        params[:players].each do |player|
          player_id, player_name = player.split("-")
          @tournament.save_kob_team_to_database(player_id, player_name, 0, false)
        end
        flash[:success] = "#{'Player'.pluralize(params[:players].length)} added"
        redirect_to tournament_path(@tournament)
      else
        @players = User.available_users(@tournament.id)
        flash[:danger] = "You didnt add any players"
        render :add_team
      end
    else
      flash[:danger] = "Not ready for that functionality yet"
      redirect_to tournament_path(@tournament)
    end
  end

  def update
    if @tournament.poolplay_started && params[:poolplay] && params[:poolplay][:registration_open]
      flash[:danger] = "Poolplay has already started can not open registration"
      redirect_to tournament_path(@tournament)
    end

    @tournament.update(tournament_params)
    if @tournament.save
      flash[:success] = "Tournament has been updated"
      redirect_to tournament_path(@tournament)
    else
      flash[:danger] = "Tournament has not been updated"
      render :edit
    end
  end

  def delete_team
    Team.find(params[:team_id]).destroy
    flash[:info] = "Team has been removed"
    redirect_to tournament_path(@tournament)
  end

  def destroy
    if @tournament.closed && @tournament.destroy
      flash[:info] = "Tournament has been deleted"
      redirect_to tournaments_path
    else
      flash[:danger] = "Tournament has not been deleted.  It must be closed first"
      redirect_to tournaments_path
    end
  end

  protected

  def resource_not_found(error)
    flash[:danger] = "The tournament you are looking for could not be found"
    redirect_to root_path
  end

  private

    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    def tournament_params
      params.require(:tournament).permit(:name, :date, :tournament_type, :registration_open, :poolplay_started, :poolplay_finished, :closed)
    end

    def set_user
      @user = current_user
    end

    def restrict_access
      unless @user && @user.admin?
        flash[:danger] = "You do not have access to that page"
        redirect_to root_path
      end
    end

    def set_teams
      @teams = @tournament.sort_teams_by_points
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  def ready_to_start_poolplay?
    !@tournament.poolplay_started && !@tournament.registration_open &&
    (@tournament.teams.length > 0 && @tournament.teams.length % 4 == 0)
  end

  def sort_teams_by_points(teams)
    teams.sort {|team1, team2| team2.total_points <=> team1.total_points }
  end
end

app/views/tournaments/_add_player_form.html.erb
<h3>Player info</h3>
<%= form_tag(add_team_path(@tournament.id), method: :post)  do %>
  <%= label_tag :first_name %>
  <%= text_field_tag :first_name %>

  <%= label_tag :last_name %>
  <%= text_field_tag :last_name %>

  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= submit_tag "Add Player", class: "btn btn-primary" %>
<% end %>

app/views/tournaments/_admin_player_form.html.erb
<div class="d-flex flex-column mt-3">
  <h4>Choose Players</h4>
  <%= form_tag(add_team_path(@tournament.id), method: :post)  do %>
    <% @players.each do |player| %>
      <div class="checkbox">
        <label>
          <%= check_box_tag "players[]", "#{player.id}-#{player.first_name}", false, class: "all_players" %>
          <%= player.first_name.capitalize %>
        </label>
      </div>
    <% end %>

    <%= submit_tag "Add Player(s)", class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/tournaments/_form.html.erb
<div>
  <div class="form_container">
    <%= form_for @tournament, html: {class: "", role: "form"} do |f| %>
      <%= render 'shared/errors', object: @tournament %>
      <div class="form-group row">
        <%= f.label :name, value: 'Name:', class: 'col-2 col-form-label' %>
        <div class="col-10">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of Tournament", autofocus: true %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :date, value: 'Date:', class: 'col-2 col-form-label' %>
        <div class="col-10">
          <%= f.date_field :date, class: 'form-control', placeholder: "Date of Tournament" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :type, value: 'Type:', class: 'col-2 col-form-label' %>
        <div class='col-10'>
          <div class="form_radio">
            <%= f.radio_button :tournament_type, 'kob' %>
            <%= f.label :tournament_type_kob, 'KOB' %>
          </div>
          <div class="form_radio">
            <%= f.radio_button :tournament_type, "team", disabled: true %>
            <%= f.label :tournament_type_team, "Team" %>
          </div>
          <div class="form_radio">
            <%= f.radio_button :tournament_type, "kob/team", disabled: true%>
            <%= f.label :tournament_type_team, "KOB/Team" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="">
          <%= f.submit class: "btn btn-primary btn-block" %>
        </div>
        <div class="mt-2">
          <% if @tournament.new_record? %>
            <%= link_to "Cancel", root_path, class: "btn btn-danger btn-block"%>
          <% else %>
            <%= link_to "Cancel", tournament_path(@tournament) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tournaments/_team.html.erb
<% if @tournament.tournament_type == 'kob' || @tournament.tournament_type == 'kob/team' %>
  <% if @tournament.teams.empty? %>
    <tr>
      <td colspan="4">No Players added yet</td>
    </tr>
  <% else %>
    <% cache(team) do %>
      <tr>
        <td class="rank"><%= team_counter + 1 %></td>
        <td class="player"><%= link_to team.team_name, player_path(team.user_id) %></td>
        <td class="points"><%= team.total_points %></td>
        <% if @user && @user.admin? && @tournament.registration_open && !@tournament.closed %>
          <td class="action">
            <%= link_to delete_team_path(@tournament, team_id: team.id), method: "delete", remote: true do %>
              <i class="fa fa-trash fa-2x text-danger" ></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
<% else %>
  <tr>
    <td colspan="4">No Teams added yet</td>
  </tr>
<% end %>

app/views/tournaments/_tournament.html.erb
<tr data-id="<%= tournament.id %>">
  <td class="tourn-field"><%= link_to tournament.name, tournament_path(tournament)%></td>
  <td class="date" ><%= normalize_date_table(tournament.date) %></td>
  <td class="type" ><%= tournament.tournament_type.upcase %></td>
  <% if !tournament.closed %>
    <td class="reg" ><%= tournament.registration_open ? 'Open' : 'Closed' %></td>
  <% end %>
  <% if tournament.closed %>
    <td class="results"><%= link_to "Final Results", final_results_path(tournament), remote: true, format: 'js' %></td>
  <% end %>
  <% if @user && @user.admin? %>
    <% if tournament.closed %>
      <td class="action-row action">
        <%= link_to tournament_path(tournament), id: "delete", method: "delete", data: { confirm: "Are you sure" } do %>
          <i class="fa fa-trash fa-2x"></i>
        <% end %>
      </td>
    <% else %>
      <% if !tournament.poolplay_started && tournament.registration_open %>
        <td class="action-row action">
          <%= link_to "Add", add_team_path(tournament.id), class: "btn btn-sm btn-success" %>
        </td>
      <% else %>
        <td class="action-row action">N/A</td>
      <% end %>
    <% end %>
  <% end %>
</tr>

app/views/tournaments/add_team.html.erb
<h2 class="text-center">Add Player to Tournament</h2>
<div class="signup_form ml-auto mr-auto">
  <%= render 'shared/errors', object: @user %>
  <% if @tournament.tournament_type == 'kob' || @tournament.tournament_type == 'kob/team' %>
    <% if @user.admin %>
      <%= render 'admin_player_form' %>
    <% else %>
      <%= render 'add_player_form' %>
    <% end %>
  <% else %>
    <%= render 'add_team_form' %>
  <% end %>
</div>

app/views/tournaments/edit.html.erb
<h2 class='text-center'>Edit Tournament</h2>
<%= render 'form' %>

app/views/tournaments/index.html.erb
<div id="tournaments-list">
  <div class="open">
    <h2 class="text-center">Active Tournaments</h2>
    <% if @user && @user.admin? %>
      <div class="admin-create p-1">
        <%= link_to "  Create New Tournament", new_tournament_path, class: "fa fa-plus" %>
      </div>
    <% end %>
    <table class="table table-tourns">
      <thead>
        <tr>
          <th class="tourn-field" scope="col">Tournament</th>
          <th class="date" scope="col">Date</th>
          <th class="type" scope="col">Type</th>
          <th class="reg" scope="col">Registration</th>
          <% if @user && @user.admin? %>
            <th class="action" scope="col">Action</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% if @tournaments_active.empty? %>
          <tr>
            <td colspan="4">No Tournaments</td>
          </tr>
        <% else %>
          <%= render @tournaments_active, cache: true %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="closed">
    <h2 class="text-center">Closed Tournaments</h2>
    <table class="table table-tourns">
      <thead>
        <tr>
          <th class="tourn-field" scope="col">Tournament</th>
          <th class="date" scope="col">Date</th>
          <th class="type" scope="col">Type</th>
          <th class="results" scope="col">Results</th>
          <% if @user && @user.admin? %>
            <th class="action" scope="col">Action</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% if @tournaments_closed.empty? %>
          <tr>
            <td colspan="4">No Tournaments</td>
          </tr>
        <% else %>
          <%= render @tournaments_closed, cache: true %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tournaments/join.html.erb
<h2 class="text-center">Add Player to Tournament</h2>
<div id="signup_form">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= render 'shared/errors', object: @user %>
      <h3>Player info</h3>
      <%= form_tag(join_path(@tournament.id), method: :post)  do %>
        <%= label_tag :first_name %>
        <%= text_field_tag :first_name %>

        <%= label_tag :last_name %>
        <%= text_field_tag :last_name %>

        <%= label_tag :email %>
        <%= email_field_tag :email %>

        <%= submit_tag "Add Player", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tournaments/new.html.erb
<h2 class='text-center'>Create New Tournament</h2>
<div>
  <%= render 'form' %>
</div>

app/views/tournaments/show.html.erb
<div id="tourn-home">

  <div id="tourn-header">
    <div class="tourn-title">
      <h2 class="text-center">
        <%= @tournament.name %>
      </h2>
    </div>

    <div class="tourn-info">
      <div id="checks">
        <div class="points">
          <% if @tournament.registration_open == false %>
          <label class="checked" for="players-check">Players Selected</label>
          <span>✅</span>
          <% else %>
          <label for="players-check">Players Selected</label>
          <% end %>
        </div>
        <div class="points">
          <% if @tournament.poolplay_started? %>
          <label class="checked" for="pool-check">Pool Play Created</label>
          <span>✅</span>
          <% else %>
          <label for="pool-check">Pool Play Created</label>
          <% end %>
        </div>
        <div class="points">
          <% if @tournament.poolplay_finished? %>
          <label class="checked" for="finish-pool">Pool Play Finished</label>
          <span>✅</span>
          <% else %>
          <label for="finish-pool">Pool Play Finished</label>
          <% end %>
        </div>
        <div class="points">
          <% if @tournament.closed? %>
          <label class="checked" for="finish-tourn">Playoffs Finished</label>
          <span>✅</span>
          <% else %>
          <label for="finish-tourn">Playoffs Finished</label>
          <% end %>
        </div>
      </div>

      <div class="tourn-type">
        <h3 class="text-center"><%= normalize_date_table(@tournament.date) %></h3>
        <h4 class="text-center">
          TYPE: <%= @tournament.tournament_type.upcase %>
        </h4>
        <% if @user && @user.admin? %>
        <div class="text-center">
          <small class="text-center m-0 edit-tourn"
            >(<%= link_to "Edit", edit_tournament_path(@tournament) %>)</small
          >
        </div>
        <% end %>
      </div>
    </div>

    <div class="tournament-play-links">
      <% if @tournament.poolplay_started %> <%= link_to "Pool Play",
      poolplay_path(@tournament.id) %> <% end %> <% if
      @tournament.playoffs_started %> <%= link_to "Playoffs",
      playoffs_path(@tournament) %> <% end %>
    </div>
  </div>
  <% cache(@tournament) do %>
  <table class="table">
    <thead>
      <tr>
        <th class="rank" scope="col">rank</th>
        <% if @tournament.tournament_type == 'kob' ||
        @tournament.tournament_type == 'kob/team' %>
        <th class="player" scope="col">Player</th>
        <% else %>
        <th scope="col">Team</th>
        <% end %>
        <th class="points" scope="col">Total Points</th>
        <% if @user && @user.admin? && @tournament.registration_open %>
        <th class="action" scope="col">Remove Team</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'tournaments/team', collection:
      sort_teams_by_points(@tournament.poolplay_team_objects), cache: true %>
    </tbody>
  </table>
  <% end %>
  <p class="disclaimer">
    * Total number of players needs to be a multiple of 4 to start pool play
  </p>

    <% if @current_user && @current_user.admin? && !@tournament.poolplay_started
    %>
    <div class="tourn-actions">
      <% if @tournament.registration_open %> <%= link_to "Add
      #{@tournament.tournament_type == 'kob' ? 'Player' : 'Team'}",
      add_team_path(@tournament.id), class: "btn btn-md btn-success" %> <% end
      %> <%= link_to "#{@tournament.registration_open ? 'Close' : 'Open'}
      Registration", tournament_path(:tournament => {registration_open:
      !@tournament.registration_open}), method: "patch", class: 'btn btn-md
      btn-primary', remote: true %> <% if ready_to_start_poolplay?%> 
      <%= link_to "Start Pool Play", new_poolplay_path(@tournament.id), class: "btn btn-primary" %> <% end %>
    </div>

    <% end %>

</div>