config/routes.rb
Rails.application.routes.draw do

  get 'landing/index'
  get 'games/index'
  get 'playoffs/index'
  get 'playoffs/new'
  get 'playoff/index'
  get 'playoff/new'
  root to: 'landing#index'
  resources :tournaments
  get '/tournaments', to: 'tournaments#index'
  get    '/tournaments/:id/add_team',    to: 'tournaments#add_team', as: :add_team
  post   '/tournaments/:id/add_team',    to: 'tournaments#add_to_tournament'
  delete '/tournaments/:id/delete_team', to: 'tournaments#delete_team', as: :delete_team

  get   '/tournaments/:id/poolplay',           to: 'poolplays#index', as: :poolplay
  get   '/tournaments/:id/poolplay/new',       to: 'poolplays#new',   as: :new_poolplay
  get   '/tournaments/:id/poolplay/temp_pool', to: 'poolplays#create_temporary_pool', as: :create_temp_pool
  post  '/tournaments/:id/poolplay',           to: 'poolplays#create'
  get   '/tournaments/:id/poolplay/edit',      to: 'poolplays#edit',  as: :results_poolplay
  patch '/tournaments/:id/poolplay',           to: 'poolplays#update'
  put   '/tournaments/:id/poolplay',           to: 'poolplays#update'
  post  '/tournaments/:id/poolplay_finished',  to: 'poolplays#poolplay_finished', as: :poolplay_finished
  get   '/tournaments/:id/poolplay/leaderboard',   to: 'poolplays#leaderboard', as: :poolplay_leaderboard

  get   '/tournaments/:id/playoffs',             to: 'playoffs#index', as: :playoffs
  post  '/tournaments/:id/playoffs',             to: 'playoffs#create'
  get   '/tournaments/:id/playoffs/edit',        to: 'playoffs#edit',  as: :results_playoffs
  patch '/tournaments/:id/playoffs',             to: 'playoffs#update'
  put   '/tournaments/:id/playoffs',             to: 'playoffs#update'
  post  '/tournaments/:id/playoffs_finished',    to: 'playoffs#playoffs_finished', as: :playoffs_finished
  get   '/tournaments/:id/final_results',        to: 'playoffs#final_results', as: :final_results
  get   '/tournaments/:id/playoffs/leaderboard', to: 'playoffs#leaderboard', as: :playoffs_leaderboard


  # resources :users
  get '/players',          to: 'users#index'
  get '/signup',           to: 'users#new', as: :new_session
  post '/signup',          to: 'users#create'
  get '/players/:id',      to: 'users#show', as: :player
  get '/players/:id/edit', to: 'users#edit', as: :edit_player
  patch '/players/:id',    to: 'users#update'
  put '/players/:id',      to: 'users#update'

  get   '/players/:id/edit_password', to: 'users#edit_password', as: :edit_password
  patch '/players/:id/edit_password', to: 'users#update_password'
  put   '/players/:id/edit_password', to: 'users#update_password'




  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :teams
  has_many :tournaments, through: :teams

  has_secure_password

  validates :first_name, presence: true
  # validates :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, on: :create, length: {minimum: 6}

  def admin?
    self.admin
  end

  def self.available_users(tourn_id)
    teams_already_added = Tournament.find(tourn_id).teams.map { |team| team.user_id }
    User.where.not(id: teams_already_added)
  end

  #Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns random token for remember me cookie
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest,  nil)
  end

  # Returns true if the given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def tournaments_played
    # tournaments ids from past tournaments played in
    # team-playoffs ids from
    # just for kob tournaments now (lookup just user_id in Team)
    Team.where(user_id: self.id, playoffs: true).map do |team|
      tourn = Tournament.find_by_id(team.tournament_id)
      points = tourn.points_earned_kob
      place = team.place.to_i
      points_earned = points[place - 1]
      { tourn_name: tourn.name, tourn_id: tourn.id, tourn_date: tourn.date, place: place, points: points_earned }
    end
  end
end

app/controllers/poolplays_controller.rb
class PoolplaysController < ApplicationController
  include PoolplaysHelper
  include TournamentsHelper
  include GamePlayable

  # creats @tournament
  before_action :set_tournament
  before_action :set_user

  # creates @poolplay
  before_action :set_poolplay, except: [:new, :create, :create_temporary_pool, :final_results, :leaderboard]

  # if still in poolplay sets Tournament poolplay_finished to true stays in poolplay_path
  before_action :start_playoffs

  # restricts starting a new poolplay
  before_action :start_pool_play_access, only: [:new, :create_temporary_pool, :create]

  #restricts access if Tournament is set to registration_open == false or
  #there are no teams entered or team number is not divisiible by 4
  before_action :restrict_access

  before_action :validate_team_numbers, only: [:new, :create]

  def index
    @current_user = current_user
    @game = 'poolplay'
  end

  def new
    if @tournament.poolplay_started
      redirect_to poolplay_path(@tournament.id)
    end
    @temp_pool = session[:temp_pool]
  end

  def create_temporary_pool
    type = @tournament.tournament_type
    if type == 'kob' || 'kob/team'
      @temp_pool_now = @tournament.create_random_kob_poolplay()
      #{1: [3, 4, 8, 5], 2: [1, 2, 7, 6]}
    else
      @temp_pool_now = @tournament.create_random_team_poolplay()
    end
    session[:temp_pool] = @temp_pool_now

    respond_to do |format|
      format.html { redirect_to new_poolplay_path @tournament.id }
      format.js {}
      format.json { render json: @temp_pool_now}
    end
    # redirect_to new_poolplay_path(@tournament)
  end

  #params["pool"] = {1: [3, 4, 8, 5], 2: [1, 2, 7, 6]}
  def create
    kob = @tournament.tournament_type == 'kob' || @tournament.tournament_type == 'kob/team'
    pool = nil

    if session[:temp_pool]
      if kob
        pool = @tournament.save_kob_games_to_database(params["pool"], "poolplay")
        @tournament.update_team_court_id(params["pool"])
      else
        pool = @tournament.save_team_play_to_database(params["pool"], "poolplay")
      end
    else
      if kob
        pool = Game.create_seeded_kob_poolplay(@tournament)
      else
        pool = Game.create_seeded_teams_poolplay(@tournament)
      end
    end

    if pool
      Tournament.update(@tournament.id, poolplay_started: true)
      flash[:success] = "Pool play has started"
      session[:temp_pool] = nil
      redirect_to poolplay_path(@tournament)
    else
      flash[:danger] = "Something went wrong"
      redirect_to tournament_path(@tournament)
    end
  end

  def edit
    game_id = params[:pool_id].to_i #|| params[:playoff_id]
    @game = @tournament.poolplay_games.select {|game| game.id == game_id}.first
    @team_1, @team_2 = team_name_with_team_number_array(@game.team_ids)
    if @game.winner
      @winner = @game.winner
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    game_id = params[:game_id].to_i
    game = Game.find(game_id)

    edited = ActiveRecord::Type::Boolean.new.cast(params[:edited])
    if edited
      game.update_play_for_editing(@tournament.tournament_type, false)
    end

    if params[:game][:winner].nil?
      flash[:danger] = "You need to select a winner"
    elsif params[:game][:score].empty? || params[:game][:score].nil? || params[:game][:score].match(/\A[2]\d+-\d{1,2}\z/).nil?
      flash[:danger] = "Score entered incorrectly"
    else
      game.update(game_params)
      if game.save
        # move out of Playable and into model(out of class method)
        game.update_play(@tournament.tournament_type, false)
        ActionCable.server.broadcast 'results_channel',
                                      game: render_results(game),
                                      game_id: game.id,
                                      playoffs: false,
                                      last_game: @poolplay && @poolplay.none? {|game| game["score"].nil? } && !@tournament.poolplay_finished

      else
        flash[:danger] = "Score was not entered"
      end
    end

    # render poolplay_path(@tournament)
  end

  def leaderboard
    @court = params["court_id"].to_i
    @in_playoffs = false
    @teams = @tournament.get_court_standings(@court, @in_playoffs)
  end

  def poolplay_finished
    if @poolplay && @poolplay.none? {|game| game["score"].nil? } && !@tournament.poolplay_finished
      Tournament.update(@tournament.id, poolplay_finished: true)
      redirect_to(poolplay_path(@tournament))
    end
    redirect_to poolplay_path(@tournament)
  end

  private
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    def start_pool_play_access
      if @tournament.poolplay_started
        flash[:danger] = "You can not access this page, pool play has already started"
        redirect_to poolplay_path(@tournament)
      end
    end

    def set_poolplay
      @poolplay = @tournament.poolplay_games
      if @poolplay.empty?
        redirect_to new_poolplay_path(@tournament.id)
      end
      @courts = divide_pool_by_courts(@poolplay)
    end

    def restrict_access
      if @tournament.registration_open || @tournament.teams.length == 0 || @tournament.teams.length % 4 != 0
        flash[:danger] = "You can not enter pool play"
        redirect_to tournament_path(@tournament)
      end
    end

    def validate_team_numbers
      if @tournament.teams.length % 4 != 0
        flash[:danger] = "You do not have the right amount of teams.  Must be multiples of 4"
        redirect_to tournament_path(@tournament)
      end
    end

    def start_playoffs # all
      if @poolplay.nil?
        return
      end
      if @poolplay.none? {|game| game["score"].nil? } && !@tournament.poolplay_finished
        Tournament.update(@tournament.id, poolplay_finished: true)
        redirect_to(poolplay_path(@tournament))
      end
    end
end

app/helpers/poolplays_helper.rb
module PoolplaysHelper
  def find_differential(score)
    if score.nil?
      return 0
    end
    score.split("-").map(&:to_i).reduce(:-)
  end

  def find_losers(game)
    teams = game.team_ids.split('-') # '5/6-3/4'['5/6', '3/4']
    teams.select { |team| team != game.winner}.first
  end

  def create_game_title_from_team_ids(team_ids)
    players = team_ids.split("-").map do |team|
      team.split('/').map do |team_player|
        @tournament.teams.select {|player| player.id == team_player.to_i}.first.team_name.split(" ").first.capitalize
      end.join('/')
    end.join(" vs ")
  end

  # given 2 teams, creates an array with 2 arrays of team names and team ids [["Paul/Abigail", "21/23"], ["Mac/Nani", "24/25"]]
  def team_name_with_team_number_array(team_ids)
    team1_id, team2_id = team_ids.split("-")
    team1_name, team2_name = create_game_title_from_team_ids(team_ids).split(" vs ")
    [[team1_name, team1_id], [team2_name, team2_id]]
  end

  def get_names_of_team_kob(team_ids)
    player1, player2 = team_ids.split("/").map(&:to_i)

    @tournament.teams.select {|player| player.id == player1 || player.id == player2 }.map(&:team_name).join("/")
  end

  # def points_earned_kob(num_of_teams)
  #   if num_of_teams == 4
  #     return [100, 50, 25, 20]
  #   else
  #     points = [100, 50, 25, 20, 20]
  #
  #     until points.length == num_of_teams
  #       points << 10
  #     end
  #     return points
  #   end
  # end

  def get_kob_court_standings_poolplay(court_id)
    team_ids = self.poolplay_teams.select { |pool| pool.court_id == court_id && pool.version === 'poolplay'}
    team_ids = get_team_ids_from_court()
  end

  def get_kob_court_standings_playoffs(court_id)
    pool = tournament.playoff_games.select { |pool| pool.court_id == court_id }

  end

  def get_court_standings(court_id, stage, tournament)
    pool = nil
    if stage == 'poolplay'
      pool = tournament.poolplay_games.select { |pool| pool.court_id == court_id}
    else
      pool = tournament.playoff_games.select { |pool| pool.court_id == court_id }
    end
    team_ids = get_teams_ids_from_court(pool)
    poolplay_standings(team_ids, tournament.teams)
  end

  def get_teams_ids_from_court(games)
    games.map {|game| game["team_ids"]}.first.split("-").map do |team|
      team.split("/")
    end.flatten.map(&:to_i)
  end

  def sort_teams_by_record_points(group)
    group.sort_by do |team|
      team_wins, team_losses = team.pool_record.split("-").map(&:to_i)
      [team_wins, team.pool_diff]
    end.reverse
  end

  # returns an array of Team objects sorted by wins and pool_diff
  def poolplay_standings(team_ids, teams)
    group = teams.select { |team| team_ids.include?(team.id) }
    sort_teams_by_record_points(group)
  end
end

app/views/poolplays/_games_table.html.erb
<% courts.keys.each do |court| %>
  <% if court == 100 %>
    <h3>Championship Court</h3>
  <% elsif court > 100 %>
    <h3>Consolation Court</h3>
  <% else %>
    <h3>Court <%= court %></h3>
  <% end %>
  <%= link_to "Leader Board", leaderboard_path(@tournament, court_id: court), format: "js", remote: true %>
  <table class="pool table">
    <thead>
      <tr class="row">
        <th scope="col">Games</th>
        <th scope="col">Score</th>
        <th scope="col">Winner(Diff)</th>
        <th scope="col">Loser(Diff)</th>
      </tr>
    </thead>
    <tbody>
      <% courts[court].each do |game| %>
        <tr id="pool_<%= game["id"] %>" data-pool_id="<%= game["id"] %>" class="row">
          <td>
            <%= create_game_title_from_team_ids(game["team_ids"]) %>
            <% if @current_user && @current_user.admin? %>
              <%= link_to "(Edit)", "#" %>
            <% end %>
          </td>
          <% if game["score"].nil? %>
            <td>
              <%= link_to "Results", results_poolplay_path(@tournament,
              pool_id: game["id"]), class: 'btn btn-primary btn-md',
              remote: true, data: { target: '#modal-window', toggle: 'modal'}
              %>
            </td>
            <td></td>
            <td></td>
            <td></td>
          <% else %>
            <%= render 'results_display', game: game %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/poolplays/_leaderboard_list.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <% if @in_playoffs %>
    <h3 class="modal-title" id="myModalLabel"><%= @court == 100 ? 'Championship' : 'Consolation'  %> Court</h3>
  <% else %>
    <h3 class="modal-title" id="myModalLabel">Leader Board: Court <%= @court  %></h3>
  <% end %>
</div>

<div class="modal-body">
  <ul id="leader_board row">
    <% @teams.each_with_index do |team, i| %>
      <li class="player_rank">
        <span class="rank"><%= i + 1 %>.</span>
        <span class="team_name"> <%= team.team_name %></span>
        <% if @in_playoffs %>
          <span class="diff"> <%= team.playoffs == '0' ? '0' : sprintf("%+d", team.playoffs) %></span>
        <% else %>
          <span class="diff"><%= team.pool_diff == 0 ? '0' : sprintf("%+d", team.pool_diff) %></span>
        <% end %>
      </li>
    <% end %>
  </ul>
<div class="modal-footer">
</div>

app/views/poolplays/_temp_pool_partial.html.erb
<!-- object = {1: [3, 4, 8, 5], 2: [1, 2, 7, 6]} -->
<% object.keys.each do |court| %>
  <h3>Court <%= court %></h3>
  <ul>
  <% object[court].each do |player| %>
    <li><%= User.find(Team.find(player).user_id).first_name %></li>
  <% end %>
  </ul>
<% end %>
<br />
<%= link_to "Use this pool", poolplay_path(@tournament.id, pool: object), method: 'post', class: "btn btn-md btn-success", data: {pool: object} %>

app/views/poolplays/create_temporary_pool.js.erb
$("#temp_pool_location").text("")
$("<%= escape_javascript(render partial: 'temp_pool_partial', locals: {object: @temp_pool_now}) %>").appendTo("#temp_pool_location")

app/views/poolplays/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'results_form' %>");
$("#modal-window").modal('show');

app/views/poolplays/index.html.erb
<% unless @tournament.poolplay_started %>
  <% link_to "Create Pools", new_poolplay_path(@tournament.id) %>
<% else %>
  <div class="play-content">
    <h2 class="text-center">POOL PLAY</h2>
    <div class="tournament-play-links">
      <%= link_to "Tournament Home", tournament_path(@tournament.id) %>
      <% if @tournament.playoffs_started %>
        <%= link_to "Playoffs", playoffs_path(@tournament) %>
      <% end %>
      <% if @tournament.closed %>
        <%= link_to "Final Results", final_results_path(@tournament), remote: true, format: 'js' %>
      <% end %>
    </div>
    <div class="game-play">
      <% if @tournament.tournament_type == 'kob' || @tournament.tournament_type == 'kob/team' %>
        <%= render 'shared/kob_games_table', courts: @courts, game: @game %>
      <% else %>
        <%= render 'shared/team_poolplay_table', courts: @courts, game: @game %>
      <% end %>
    </div>
  </div>
<% end %>
<% if @tournament.poolplay_finished && !@tournament.playoffs_started  && (@current_user && @current_user.admin?) %>
  <%= link_to "Start Playoffs", playoffs_path(@tournament), method: 'post', class: "btn btn-lg btn-primary" %>
<% end %>
<%= link_to "", poolplay_finished_path(@tournament), method: 'post', id: 'poolplay_finished', type: 'hidden' %>

app/views/poolplays/leaderboard.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'leaderboard_list' %>");
$("#modal-window").modal('show');

app/views/poolplays/new.html.erb
<h1>Start Pool Play </h1>
<%= link_to "Create temporary pool", create_temp_pool_path(@tournament.id), data: {id: @tournament.id}, remote: true, id: "temp_pool", class: 'btn btn-primary btn-md' %>

<div id="temp_pool_location">
  <% if @temp_pool %>
    <%= render 'temp_pool_partial', object: @temp_pool %>
    <!-- object = {1: [3, 4, 8, 5], 2: [1, 2, 7, 6]} -->
  <% end %>
</div>