config/routes.rb
Rails.application.routes.draw do

  get 'landing/index'
  get 'games/index'
  get 'playoffs/index'
  get 'playoffs/new'
  get 'playoff/index'
  get 'playoff/new'
  root to: 'landing#index'
  resources :tournaments
  get '/tournaments', to: 'tournaments#index'
  get    '/tournaments/:id/add_team',    to: 'tournaments#add_team', as: :add_team
  post   '/tournaments/:id/add_team',    to: 'tournaments#add_to_tournament'
  delete '/tournaments/:id/delete_team', to: 'tournaments#delete_team', as: :delete_team

  get   '/tournaments/:id/poolplay',           to: 'poolplays#index', as: :poolplay
  get   '/tournaments/:id/poolplay/new',       to: 'poolplays#new',   as: :new_poolplay
  get   '/tournaments/:id/poolplay/temp_pool', to: 'poolplays#create_temporary_pool', as: :create_temp_pool
  post  '/tournaments/:id/poolplay',           to: 'poolplays#create'
  get   '/tournaments/:id/poolplay/edit',      to: 'poolplays#edit',  as: :results_poolplay
  patch '/tournaments/:id/poolplay',           to: 'poolplays#update'
  put   '/tournaments/:id/poolplay',           to: 'poolplays#update'
  post  '/tournaments/:id/poolplay_finished',  to: 'poolplays#poolplay_finished', as: :poolplay_finished
  get   '/tournaments/:id/poolplay/leaderboard',   to: 'poolplays#leaderboard', as: :poolplay_leaderboard

  get   '/tournaments/:id/playoffs',             to: 'playoffs#index', as: :playoffs
  post  '/tournaments/:id/playoffs',             to: 'playoffs#create'
  get   '/tournaments/:id/playoffs/edit',        to: 'playoffs#edit',  as: :results_playoffs
  patch '/tournaments/:id/playoffs',             to: 'playoffs#update'
  put   '/tournaments/:id/playoffs',             to: 'playoffs#update'
  post  '/tournaments/:id/playoffs_finished',    to: 'playoffs#playoffs_finished', as: :playoffs_finished
  get   '/tournaments/:id/final_results',        to: 'playoffs#final_results', as: :final_results
  get   '/tournaments/:id/playoffs/leaderboard', to: 'playoffs#leaderboard', as: :playoffs_leaderboard


  # resources :users
  get '/players',          to: 'users#index'
  get '/signup',           to: 'users#new', as: :new_session
  post '/signup',          to: 'users#create'
  get '/players/:id',      to: 'users#show', as: :player
  get '/players/:id/edit', to: 'users#edit', as: :edit_player
  patch '/players/:id',    to: 'users#update'
  put '/players/:id',      to: 'users#update'

  get   '/players/:id/edit_password', to: 'users#edit_password', as: :edit_password
  patch '/players/:id/edit_password', to: 'users#update_password'
  put   '/players/:id/edit_password', to: 'users#update_password'




  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav id="navbar" class="navbar navbar-expand-sm navbar-dark bg-dark">
  <%= link_to "Tournament Tracker", tournaments_path, class: "navbar-brand" %>
  <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="">
      <i class="fa fa-navicon"></i>
    </span>
  </button>
  <div class="collapse navbar-collapse justify-content-stretch" id="navbarContent">
    <div class="navbar-nav ml-auto">
      <% if user_logged_in? %>
        <%= link_to @user.first_name, player_path(@user), class: "nav-item nav-link"%>
        <%= link_to "Log out", logout_path, class: "nav-item nav-link" %>
      <% else %>
        <%= link_to "Sign up", signup_path, class: "nav-item nav-link" %>
        <%= link_to "Log in", login_path, class: "nav-item nav-link" %>
      <% end %>
      <%= link_to "Players", players_path, class: " nav-item nav-link" %>
      <% if @user && @user.admin? %>
        <%= link_to "Create New Player", signup_path, class: "nav-item nav-link" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TournamentTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
      </div>
    </div>
    <div id="App">
      <%= render 'layouts/navigation' %>
      <div id="main">
        <% flash.each do |name, msg| %>
          <div class="text-center alert alert-<%= name %>">
            <%= msg %>
          </div>
        <% end %>
        <%= yield %>
      </div>
      <footer id="footer"></footer>
    </div>
  </body>
</html>